---
# file: vhost_add.yml


- name: Apache | Create document root
  file: path=/var/www/default state=directory recurse=yes owner=www-data mode=775


# for Apache > 2.2.x VirtualHost file should not end with conf
- name: Apache | Virtualhost add | Push virtualhost configuration template
  template: src=default_virtualhost.j2 dest=/etc/apache2/sites-available/{{ vhost }}

- name: Apache | Remove default index file from default docroot
  file: path=/var/www/index.html state=absent

- name: Apache | set permissions on DocumentRoot
  file: path=/var/www/default owner=www-data group=www-data mode=775

- name: Apache | Disable default virtualhost
  command: a2dissite 000-default


- name: Apache | add user {{ admin_user }} to www-data group
  command: usermod -a -G www-data {{ admin_user }}

# for Apache > 2.2.x VirtualHost file should not end with conf
- name: Apache | Virtualhost add | Activate virtualhost
  command: /usr/sbin/a2ensite {{ vhost }} creates=/etc/apache2/sites-enabled/{{ vhost }}
  notify:
  - apache-restart
