---

- name: PHP | PECL | Insure PHP development packages are installed
  apt: pkg={{ item }} state=installed
  with_items:
    - php5-dev
    - php-pear
    - make

- name: PHP | PHP dev | update PEAR packages
  command: pear upgrade

- name: PHP | PHP dev | Set peatr auto-discover
  command: pear config-set auto_discover 1

- name: PHP | PHP dev | Pear install the PHP QA Toolchain
  command: pear install pear.phpqatools.org/phpqatools creates=/usr/bin/phpunit