---
##
# Drush install, a Drupal shell tool.
#
# Ubuntu only due to using apt.
#
- name: Drush | Install PHP PEAR
  action: apt pkg=php-pear state=installed
#  tags: drush


- name: Drush | install via Composer
  command: composer global require drush/drush:6.*
  sudo: no

- name: Drush | make drush command accesible
  command: ln -sfn /home/{{ admin_user }}/.composer/vendor/drush/drush/drush /usr/bin/drush

#- name: Drush | Update PEAR
#  action: command pear upgrade-all
#  tags: drush

#- name: Drush | Setup PEAR channel
#  action: command pear channel-discover pear.drush.org creates=/usr/share/php/.channels/pear.drush.org.reg
#  tags: drush

#- name: Drush | Install drush
#  action: command pear install drush/drush creates=/usr/bin/drush
#  tags: drush

#- name: Drush | clone git repository
#  git: repo=git@github.com:drush-ops/drush.git dest=/var/www/drush

#- name: Drush | make drush command accesible
#  command: ln -s /var/www/drush/drush /usr/bin/drush
#
#- name: Drush | Run drush once so it downloads it's dependencies
#  action: command drush
#  tags: drush


